sealed class Routes(val route: String) {
    object Splash : Routes("splash")
    object Login : Routes("login")
    object Home : Routes("home")
    object Faculty : Routes("faculty")
    object Community : Routes("community")
    object AboutUs : Routes("about_us")
    object BottomNav : Routes("bottom_nav")
    object AdminDashBoard : Routes("admin_dashboard")
    object ManageBanner : Routes("manage_banner")
    object ManageFaculty : Routes("manage_routes")
    object ManageEvents : Routes("manage_events")
    object ManageTimetable : Routes("manage_timetable")
    object Register : Routes("register")
    object Settings : Routes("settings")
    object Contact : Routes("contact")
    object Timetable : Routes("Timetable")
    object Notice : Routes("notice")
    object Website : Routes("website")
    object manageNotice : Routes("manage_notice")
}
